# Generated by Django 5.0 on 2024-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myone',
            name='img',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png'),
        ),
    ]
