# Generated by Django 5.0 on 2024-09-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(default='https://assets.thehansindia.com/h-upload/2022/07/18/1303611-pro.webp'),
        ),
    ]
